version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysqlv2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - todo-net

volumes:
  mysql_data:

networks:
  todo-net:
    driver: bridge
